name: vax_cast
description: Vaccine Forecasting Tool Using Fhir Resources for Dart and Flutter

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  date_utils: ^0.1.0+3
  equatable: ^1.1.1
  http: ^0.12.0+4
  meta: ^1.1.8
  intl: ^0.16.1
  built_value: ^7.0.9
  freezed: ^0.10.7
  fhir_r4:
    path: /home/grey/dev/fhir_r4
  fhir_stu3:
    path: /home/grey/dev/fhir_stu3
  fhir_dstu2:
      path: /home/grey/dev/fhir_dstu2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  json_serializable: ^3.2.5
  build_runner: ^1.8.1
  mockito: ^4.1.1
  built_value_generator: ^7.0.9

flutter:
  uses-material-design: true