name: vax_cast
description: Vaccine Forecasting Tool Using Fhir Resources for Dart and Flutter

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  date_utils: ^0.1.0+3
  http: ^0.12.0+4
  meta: ^1.1.8
  intl: ^0.16.1
  freezed: ^0.10.7
  dartz: ^0.9.1
  fhir:
    path: /home/grey/dev/fhir

dev_dependencies:
  json_serializable: ^3.2.5
  build_runner: ^1.8.1

flutter:
  uses-material-design: true